name: Docker Build and Push to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - jm-production

jobs:
  deploy-gh-runner-aci:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          ref: jm-production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.multi
          push: true
          tags: ghcr.io/jmaddington/librechat:latest

      - name: Log out from Docker Hub
        run: docker logout ghcr.io